import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

data = {
    "text": [
        "I love this movie",
        "This film was amazing",
        "Fantastic acting and story",
        "I really enjoyed the movie",
        "What a great experience",
        "Absolutely wonderful film",
        "Brilliant screenplay and direction",
        "The actors did a superb job",
        "Highly recommended movie",
        "I liked every part of it",
        "Best movie I have seen",
        "Very inspiring and beautiful",
        "The story was heart touching",
        "Excellent performance by the cast",
        "A masterpiece of cinema",
        "Super entertaining and fun",
        "Loved the music and visuals",
        "A delightful watch",
        "Two thumbs up",
        "Great movie for family",

        "I hate this movie",
        "Worst film ever",
        "Very boring and slow",
        "Terrible acting",
        "Waste of time",
        "Not worth watching",
        "Poor storyline",
        "I did not like this movie",
        "Very disappointing film",
        "The plot was horrible",
        "Actors did a bad job",
        "I regret watching this",
        "Completely useless movie",
        "Very dull experience",
        "Awful direction",
        "No entertainment at all",
        "Bad script and acting",
        "I fell asleep watching this",
        "Pathetic movie",
        "Not recommended at all",

        "The movie was okay",
        "It was an average film",
        "Nothing special about it",
        "Some parts were good",
        "It had both good and bad moments",
        "Average acting performance",
        "Story was fine but slow",
        "Decent movie overall",
        "Watchable but not great",
        "Just a normal film",

        "I absolutely loved the performance",
        "The visuals were stunning",
        "Storytelling was brilliant",
        "The movie kept me engaged",
        "A very positive experience",
        "It made me happy",
        "I smiled throughout the film",
        "Great entertainment value",
        "Wonderful direction and music",
        "An unforgettable movie",

        "The film made no sense",
        "Confusing and boring plot",
        "Very bad experience",
        "Terrible screenplay",
        "I didn't enjoy it",
        "The movie was too long and boring",
        "Bad editing and direction",
        "Very poor performance",
        "I won't watch it again",
        "Complete disaster",

        "Loved the characters",
        "The movie was full of energy",
        "Such a pleasant surprise",
        "I was impressed by the acting",
        "Superb and engaging story",
        "Very creative and interesting",
        "The film was full of emotions",
        "I felt connected to the story",
        "A positive vibe throughout",
        "A very satisfying movie",

        "I disliked the characters",
        "The movie lacked energy",
        "Very predictable story",
        "I was not impressed",
        "Boring and uninteresting",
        "The film had no emotions",
        "I felt disconnected",
        "Negative vibe throughout",
        "Unsatisfying experience",
        "movie is bad",
        "Very forgettable movie",
        "movie is good",
        "lecture is very good",
        "The movie was fantastic and full of emotions",
        "I really loved the background music",
        "Such an outstanding performance",
        "The direction was top class",
        "I enjoyed every scene of the movie",
        "A very heartwarming story",
        "The film was beautifully shot",
        "Absolutely loved the screenplay",
        "The characters were very lively",
        "An excellent cinematic experience",

        "The movie was terrible and confusing",
        "I did not understand the story",
        "Very poorly written script",
        "The acting was below average",
        "I was bored throughout the film",
        "A complete waste of money",
        "Not engaging at all",
        "The scenes were very dull",
        "Extremely disappointing movie",
        "I will never recommend this film",

        "Nice movie with good acting",
        "It was a pleasant experience",
        "Some scenes were really impressive",
        "A decent watch for the weekend",
        "The story was simple and nice",
        "Actors performed really well",
        "Enjoyable and entertaining",
        "A feel good movie",
        "Interesting plot and execution",
        "Good effort by the team",

        "The film had too many flaws",
        "The story was very weak",
        "Bad direction and editing",
        "Unnecessary long movie",
        "I didn’t like the climax",
        "Poorly managed screenplay",
        "Very forgettable film",
        "Nothing new in the story",
        "The movie lacked creativity",
        "Very disappointing ending",

        "I loved how the story progressed",
        "Brilliant acting by the lead actor",
        "Very inspiring movie",
        "The movie gave positive vibes",
        "A joyful cinematic ride",
        "Everything about the movie was perfect",
        "Truly a masterpiece",
        "I would watch it again",
        "Very engaging and emotional",
        "A must watch film",

        "Terrible background score",
        "I couldn’t connect with the story",
        "Bad casting choices",
        "Very slow and dragging plot",
        "I almost slept watching this",
        "The movie was very irritating",
        "Worst experience ever",
        "Not worth the hype",
        "I didn’t like the screenplay",
        "The plot made no sense",

        "The film was entertaining from start to end",
        "Great combination of story and acting",
        "Really loved the dialogues",
        "The movie had a strong message",
        "A wonderful experience",
        "Excellent storytelling",
        "The visuals were very attractive",
        "Superb work by the director",
        "I liked the screenplay a lot",
        "Very impressive movie",

        "I disliked most of the scenes",
        "The movie had no direction",
        "Very poor storyline",
        "The acting felt fake",
        "Not interesting at all",
        "A boring cinematic experience",
        "I would not suggest this movie",
        "Very bad execution",
        "The movie was full of mistakes",
        "Highly disappointing",
        "A very positive and energetic film",
        "Loved the overall concept",
        "Great movie with good lessons",
        "The actors gave their best",
        "One of the best movies recently",
        "The film was full of creativity",
        "Very emotional and touching",
        "A delightful movie experience",
        "The story kept me hooked",
        "Fantastic movie overall",
        "I literally hate the movie"
    ],

    "label": [
        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",
        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",

        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",
        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",

        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",

        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",

        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",

        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",

        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",
        "negative","positive","positive","positive","positive","positive","positive","positive","positive","positive",
        "positive","positive","positive","negative","negative","negative","negative","negative","negative","negative",
        "negative","negative","negative",
        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",
        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",
        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",
        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",
        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",
        "negative","negative","negative","negative","negative","negative","negative","negative","negative","negative",
        "positive","positive","positive","positive","positive","positive","positive","positive","positive","positive",
        "negative"
    ]
}

df = pd.DataFrame(data)

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["text"])

model = MultinomialNB()
model.fit(X, df["label"])

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model and vectorizer saved successfully!")
